config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :questions do
    resources :answers, only: [:create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :content, presence: true, length: {minimum: 5}
  validates :user_id, presence: true
  validates :question_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :answers

  validates :title, presence: true, length: {minimum: 2}
  validates :content, presence: true, length: {minimum: 5}
  validates :user_id, presence: true
  validates :topic_id, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: {minimum: 2}

  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true, length: {minimum: 3}

  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    authorize(@answer)
    @answer.user = current_user
    @question = Question.find(params[:question_id])
    @answer.question = @question

    if @answer.save
      redirect_to question_path(@question)
    else
      render "questions/show"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_question, only: [:show, :destroy]

  def index
    @questions = policy_scope(Question).all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
    authorize(@question)
    @topics = Topic.all
  end

  def create
    @question = Question.new(question_params)
    authorize(@question)
    @question.user = current_user
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

  def find_question
    @question = Question.find(params[:id])
    authorize(@question)
  end

  def question_params
    params.require(:question).permit(:title, :content, :topic_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stackoverrun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/questions/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 col-md-8">
      <h1>Questions</h1>

      <ul>
        <% @questions.each do |question| %>
          <li>
            <%= link_to question.title, question_path(question) %> - 
            <%= question.user.username %>
            <%= link_to "Delete", question_path(question), method: :delete, data: {confirm: "Are you sure?"} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="container">
  <div class="row justify-content-center">
    <col-4 class="col-md-6">
      <%= simple_form_for @question do |f| %>
        <%= f.input :title %>
        <%= f.input :content %>
        <%= f.input :topic_id, collection: @topics %>
        <%= f.button :submit %>
      <% end %>
    </col-4>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <col-4 class="col-md-6">
      <h1><%= @question.title %></h1>

      <p><%= @question.content %></p>

      <ul>
        <% @question.answers.each do |answer| %>
          <li><%= answer.content %> - <%= answer.user.username %></li>
        <% end %>
      </ul>

      <%= simple_form_for [@question, @answer] do |f| %>
        <%= f.input :content %>
        <%= f.button :submit %>
      <% end %>
    </col-4>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to questions_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.username, "#", class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Add Question", new_question_path, class: "nav-link" %>
        </li>

        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/#{current_user.username}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>